version: "3"
services:
    clickhouse:
     image: clickhouse/clickhouse-server
     environment:
      - CLICKHOUSE_DB=${CLICKHOUSE_DB:-orb}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER:-clickhouse-user}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD:-12345}
     ports:
     - "8123:8123"
     - "9000:9000"
     - "9009:9009"
     volumes:
     - ./db/data:/var/lib/clickhouse
     - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
     healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1
      interval: 5s
      timeout: 10s
      retries: 3
     
     ulimits:
      nproc: 65535
      nofile:
       soft: 262144
       hard: 262144