name: wr
services:
  clickhouse:
    build:
      context: ..
    image: clickhouse/clickhouse-server:24.6
    environment:
      - CLICKHOUSE_DB=${CLICKHOUSE_DB:-wv}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER:-user}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD:-12345}
    ports:
      - "8124:8123"
      - "9001:9000"
    volumes:
      - ../db/data:/var/lib/clickhouse
      - ../db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ../db/master.csv:/var/lib/clickhouse/master.csv
      - ../db/gdmi_compact.csv:/var/lib/clickhouse/gdmi_compact.csv
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1
      interval: 5s
      timeout: 10s
      retries: 3
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    extra_hosts:
      - "host.docker.internal:host-gateway"
  runner:
    image: runner
    build:
      context: ..
      dockerfile: deploy/Dockerfile.runner
    environment:
      - CONFIG_FILE=${CONFIG_FILE:-config/crawler.dev.yml}
    depends_on:
      clickhouse:
        condition: service_healthy
