name: wr
services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.1-alpine
    environment:
      - CLICKHOUSE_DB=${CLICKHOUSE_DB:-wv}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER:-user}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD:-12345}
    ports:
      - "8124:8123"
      - "9001:9000"
    volumes:
      - ../clickhouse/data:/var/lib/clickhouse
      - ../clickhouse/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ../clickhouse/dumps/master.parquet:/var/lib/clickhouse/master.parquet
      - ../clickhouse/dumps/gdmi_compact.parquet:/var/lib/clickhouse/gdmi_compact.parquet
      - ../clickhouse/dumps/two_table.parquet:/var/lib/clickhouse/two_table.parquet
      - ../clickhouse/dumps/crawler_two_table.parquet:/var/lib/clickhouse/crawler_two_table.parquet
      - ../clickhouse/dumps/two_table_tiny.parquet:/var/lib/clickhouse/two_table_tiny.parquet
      - ../clickhouse/dumps/two_table_big.parquet:/var/lib/clickhouse/two_table_big.parquet
      - ../clickhouse/dumps/two_table_huge.parquet:/var/lib/clickhouse/two_table_huge.parquet
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1
      interval: 5s
      timeout: 10s
      retries: 3
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    extra_hosts:
      - "host.docker.internal:host-gateway"

  runner:
    image: runner
    build:
      context: ..
      dockerfile: deploy/Dockerfile.runner
    environment:
      - CONFIG_FILE=${CONFIG_FILE:-config/crawler.dev.yml}
    depends_on:
      clickhouse:
        condition: service_healthy
