FROM golang:1.24 AS builder

WORKDIR /app

ENV CGO_ENABLED=0

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY cmd cmd
COPY internal internal
COPY pkg pkg
RUN mkdir ./bin && go build -v -o ./bin ./cmd/... ./pkg/...

FROM scratch AS final

WORKDIR /app

COPY --from=builder /app/bin/cmd .
COPY config /app/config

ENTRYPOINT ["/app/cmd"]
